accounts/urls.py
from django.urls import path 
from .views import login_view, logout_view, signup_view


urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('signup/', signup_view, name = 'signup'),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('receipts/', include('receipts.urls')),
    path('', RedirectView.as_view(url='/receipts/', permanent=False)),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

receipts/urls.py
from django.urls import path
from .views import (
    ReceiptListView,
    ReceiptCreateView,
    ExpenseCategoryListView,
    AccountListView,
    ExpenseCategoryCreateView,
    AccountCreateView
)

urlpatterns = [
    path('', ReceiptListView.as_view(), name='home'),  # This should be named 'home'
    path('create/', ReceiptCreateView.as_view(), name='create_receipt'),
    path('categories/', ExpenseCategoryListView.as_view(), name='category_list'),
    path('categories/create/', ExpenseCategoryCreateView.as_view(), name='create_category'),
    path('accounts/', AccountListView.as_view(), name='account_list'),
    path('accounts/create/', AccountCreateView.as_view(), name='create_account'),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.contrib.auth.models import User

class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(User, related_name="categories", on_delete=models.CASCADE)

class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(User, related_name="accounts", on_delete=models.CASCADE)

class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(max_digits=10, decimal_places=3)
    tax = models.DecimalField(max_digits=10, decimal_places=3)
    date = models.DateTimeField()
    category = models.ForeignKey(ExpenseCategory, on_delete=models.CASCADE)
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    purchaser = models.ForeignKey(User, on_delete=models.CASCADE)

accounts/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(max_length=150,widget=forms.PasswordInput)   



class SignupForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(max_length=150,widget=forms.PasswordInput)
    password_confirmation = forms.CharField(max_length=150,widget=forms.PasswordInput)

receipts/forms.py
from django import forms 
from .models import Receipt, ExpenseCategory, Account


class ReceiptForm(forms.ModelForm):
    class Meta:
        model = Receipt
        fields = ['vendor', 'total', 'tax', 'date', 'category', 'account']


class ExpenseCategoryForm(forms.ModelForm):
    class Meta:
        model = ExpenseCategory
        fields = ['name']
    


class AccountForm(forms.ModelForm):
    class Meta:
        model = Account 
        fields = ['name', 'number']


class CategoryForm(forms.ModelForm):
    class Meta:
        model = ExpenseCategory
        fields = ['name']

accounts/views.py
from django.shortcuts import render, redirect 
from django.contrib.auth import authenticate, login, logout  
from .forms import LoginForm, SignupForm
from django.contrib.auth.models import User

# Create your views here.
def logout_view(request):
    logout(request)
    return redirect('login')

    


def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('home')  
            else:
                form.add_error(None, 'Invalid username or password')
    else:
        form = LoginForm()

    return render(request, 'accounts/login.html', {'form': form})






def signup_view(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            password_confirmation = form.cleaned_data['password_confirmation']

        if password != password_confirmation:
            form.add_error('password_confirmation', 'The passwords do not match')
        else:
            user = User.objects.create_user(username=username,password=password)
            user = authenticate(username=username,password=password)
            if user is not None: 
                login(request,user)
                return redirect('home')
    else:
        form = SignupForm()

    return render(request,'accounts/signup.html',{'form':form})

receipts/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render, redirect
from .models import Receipt, ExpenseCategory, Account
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import ReceiptForm, ExpenseCategoryForm, AccountForm, CategoryForm
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy






class AccountCreateView(LoginRequiredMixin, CreateView):
    model = Account
    form_class = AccountForm
    template_name = 'receipts/account_form.html'
    success_url = reverse_lazy('account_list') 
    
    def form_valid(self, form): 
        form.instance.owner = self.request.user
        return super().form_valid(form)
    



def create_account(request):
    form = AccountForm()
    if request.method == 'POST':
        form = AccountForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
    return render(request, 'receipts/account_form.html', {'form': form})



def create_receipt(request):
    if request.method == 'POST':
        form = ReceiptForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = ReceiptForm()
    return render(request, 'create_receipt.html', {'form': form})





class ExpenseCategoryCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory 
    form_class = ExpenseCategoryForm
    template_name = 'receipts/category_form.html'
    success_url = reverse_lazy('category_list')

    def form_valid(self, form):
        form.instance.owner = self.request.user 
        return super().form_valid(form)







class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    form_class = ReceiptForm
    template_name = 'receipts/receipt_form.html'
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        form.instance.purchaser = self.request.user
        return super().form_valid(form)
    


class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = 'receipts/receipt_list.html'
    context_object_name = 'receipts'

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)
    

class ExpenseCategoryListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = 'receipts/category_list.html'
    context_object_name = 'categories' 

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)

class AccountListView(LoginRequiredMixin, ListView):
    model = Account 
    template_name = 'receipts/account_list.html'
    context_object_name = 'accounts' 


    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)
    

accounts/templates/accounts/login.html
{%extends "base.html"%}

{% block content %}

            <h1>Login</h1>
            <form action="{% url 'accounts:login' %}" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Login</button>
            </form>
       

        {% endblock content %}

accounts/templates/accounts/signup.html
{%extends "base.html"%}

{% block content %}
            <h1>Signup</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Signup</button>
            </form>
            {% endblock content %}

receipts/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My App{% endblock %}</title>
</head>
<body>
    <header>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'home' %}">Receipts</a></li>
                    <li><a href="{% url 'create_receipt' %}">Create Receipt</a></li>
                    <li><a href="{% url 'category_list' %}">Expense Categories</a></li>
                    <li><a href="{% url 'create_category' %}">Create Category</a></li>
                    <li><a href="{% url 'account_list' %}">Accounts</a></li>
                    <li><a href="{% url 'create_account' %}">Create Account</a></li>
                    <li><a href="{% url 'logout' %}">Logout</a></li>
                    
                {% else %}
                    <li><a href="{% url 'signup' %}">Sign Up</a></li>
                    <li><a href="{% url 'login' %}">Login</a></li>
                    
                {% endif %}
            </ul>
        </nav>
    </header>
    <main>
        <div>
        {% block content %}     {% endblock content %}
        </div>
    </main>
</body>
</html>

receipts/templates/receipts/account_form.html
{% extends 'base.html' %}


{% block content %}

    <div>
        <h1>Create Account</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>

{% endblock content %}

receipts/templates/receipts/account_list.html
{% extends 'base.html' %}


{% block content %}

        <h1>Accounts</h1>
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Number</th>
                    <th>Number of Receipts</th>
                </tr>
            </thead>
            <tbody>
                {% for account in accounts %}
                <tr>
                    <td>{{ account.name }}</td>
                    <td>{{ account.number }}</td>
                    <td>{{ account.receipts.count }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
  
{% endblock content %}

receipts/templates/receipts/category_form.html
{% extends 'base.html' %}



{% block content %}
<html>
<body>
<main>
    <div>
        <h1>Create Category</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
</main>
</body>
</html>
{% endblock content %}

receipts/templates/receipts/category_list.html
{% extends 'base.html' %}
{% block content %}

        <h1>Expense Categories</h1>
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Number of Receipts</th>
                </tr>
            </thead>
            <tbody>
                {% for category in categories %}
                <tr>
                    <td>{{ category.name }}</td>
                    <td>{{ category.receipts.count }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
{% endblock content %}

receipts/templates/receipts/create_account.html
{%extends "base.html"%}

{% block content %}

            <h1>Create Account</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Create</button>
            </form>
            
            {% endblock content %}

receipts/templates/receipts/create_category.html
{%extends "base.html"%}

{% block content %}
         
         
         <h1>Create Category</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Create</button>
            </form>
        

            {% endblock content %}

receipts/templates/receipts/create_receipt.html
{%extends "base.html"%}

{% block content %}

            <h1>Create Receipt</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.vendor.label_tag }} {{ form.vendor }}
                {{ form.total.label_tag }} {{ form.total }}
                {{ form.tax.label_tag }} {{ form.tax }}
                {{ form.date.label_tag }} {{ form.date }}
                {{ form.category.label_tag }} {{ form.category }}
                {{ form.account.label_tag }} {{ form.account }}
                <button type="submit">Create</button>
            </form>
 
            {% endblock content %}

receipts/templates/receipts/receipt_form.html
{% extends 'base.html' %}

{% block title %}Create Receipt{% endblock title %}

{% block content %}
  
        <h1>Create Receipt</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>

{% endblock content %}

receipts/templates/receipts/receipt_list.html
{%extends "base.html"%}

{% block content %}



        <h1>My Receipts</h1>
        <table>
            <thead>
                <tr>
                    <th>Vendor</th>
                    <th>Total</th>
                    <th>Tax</th>
                    <th>Date</th>
                    <th>Category</th>
                    <th>Account</th>
                </tr>
            </thead>
            <tbody>
                {% for receipt in receipts %}
                <tr>
                    <td>{{ receipt.vendor }}</td>
                    <td>{{ receipt.total }}</td>
                    <td>{{ receipt.tax }}</td>
                    <td>{{ receipt.date|date:"m/d/y" }}</td>
                    <td>{{ receipt.category.name }}</td>
                    <td>{{ receipt.account.name }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
  


{% endblock content %}

receipts/templates/receipts/receipts.html
{%extends "base.html"%}

{% block content %}
        <h1>My Receipts</h1>
        <table>
            <thead>
                <tr>
                    <th>Vendor</th>
                    <th>Total</th>
                    <th>Tax</th>
                    <th>Date</th>
                    <th>Category</th>
                    <th>Account</th>
                </tr>
            </thead>
            <tbody>
                {% for receipt in receipts %}
                    <tr>
                        <td>{{ receipt.vendor }}</td>
                        <td>{{ receipt.total|floatformat:3 }}</td>
                        <td>{{ receipt.tax|floatformat:3 }}</td>
                        <td>{{ receipt.date|date:"m/d/y" }}</td>
                        <td>{{ receipt.category.name }}</td>
                        <td>{{ receipt.account.name }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
 
        {% endblock content %}